ci:
  config:
    schema_version: 1
    trunk_branch: main
    cli_version: v0.16.5-rc.2
    cli_version_sha: 2231b2bee90615ffb66cdee3a3cfd410720df370
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    environments: [prod]
    triggers: [src/**]
    builds:
      - name: app
        workflow: .github/workflows/build-app.yaml
        triggers: []
    deploys:
      - name: app
        workflow: .github/workflows/deploy-app.yaml
        triggers: []
  state:
    prod:
      sha: 4e1c72048d8fee1f22ce8a1f36fde901a0e3365f
      version: v0.1.0-rc.0
      committed_at: "2026-07-19T19:41:16Z"
      committed_by: joshua-temple
      deploys:
        app:
          sha: 4e1c72048d8fee1f22ce8a1f36fde901a0e3365f
          deployed_at: "2026-07-19T19:41:16Z"
          deployed_by: joshua-temple
  latest_release:
    version: v0.1.0
    sha: 4e1c72048d8fee1f22ce8a1f36fde901a0e3365f
    released_on: "2026-07-19T19:43:23Z"
    released_by: joshua-temple
