ci:
  config:
    schema_version: 1
    trunk_branch: main
    cli_version: v0.14.0-dryrun.51
    cli_version_sha: f904ea561ac0ba556b251bca7ea8f54f492c7a54
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    environments: [prod]
    triggers: [src/**]
    builds:
      - name: app
        workflow: .github/workflows/build-app.yaml
        triggers: []
    deploys:
      - name: app
        workflow: .github/workflows/deploy-app.yaml
        triggers: []
  state:
    prod:
      sha: b6d84db290f0d6cb776abe1791aac8b108dd90dd
      version: v0.1.0-rc.0
      committed_at: "2026-07-10T06:53:39Z"
      committed_by: joshua-temple
      deploys:
        app:
          sha: b6d84db290f0d6cb776abe1791aac8b108dd90dd
          deployed_at: "2026-07-10T06:53:39Z"
          deployed_by: joshua-temple
  latest_release:
    version: v0.1.0
    sha: ce3f286887921c49c07b270d0d34806519f50dd7
    released_on: "2026-07-10T04:14:37Z"
    released_by: joshua-temple
