ci:
  config:
    schema_version: 1
    trunk_branch: main
    cli_version: v0.9.3-rc.0
    cli_version_sha: ba33a64b96ce6155673e7e73d61e097683a4086c
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    environments: [prod]
    triggers: [src/**]
    builds:
      - name: app
        workflow: .github/workflows/build-app.yaml
        triggers: []
    deploys:
      - name: app
        workflow: .github/workflows/deploy-app.yaml
        triggers: []
  state:
    prod:
      sha: a75fb21439064ebff3aab886f953acf848de68bd
      version: v0.9.3-rc.0
      committed_at: "2026-07-06T21:29:39Z"
      committed_by: joshua-temple
      deploys:
        app:
          sha: a75fb21439064ebff3aab886f953acf848de68bd
          deployed_at: "2026-07-06T21:29:39Z"
          deployed_by: joshua-temple
  latest_release:
    version: v0.1.0
    sha: a75fb21439064ebff3aab886f953acf848de68bd
    released_on: "2026-07-06T21:31:59Z"
    released_by: joshua-temple
